name: Build Client
on: [push]
jobs:
  android:
    runs-on: [ubuntu-latest]
    steps:
      - name: Check Out Code
        uses: actions/checkout@v1
      - name: Extract Signature
        run: echo ${{secrets.KEY_FILE}} | base64 -d > $HOME/.android.jks
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
      - name: Build APK
        run: flutter build apk --target-platform android-arm
        env:
          KEY_PASS: ${{secrets.KEY_PASS}}
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: drc-client-android
          path: build/app/outputs/flutter-apk/app-release.apk
  desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: drc
            platfrom: linux
            bundle-path: build/linux/x64/release/bundle
          - os: macOS-latest
            output-name: drc
            platfrom: macos
            bundle-path: build/macos/Build/Products/Release/docker_register_cloud.app
          - os: windows-latest
            output-name: drc.exe
            platfrom: windows
            bundle-path: build/windows/runner/release
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
      - run: sudo apt-get update -y
        if: matrix.os == 'ubuntu-latest'
      - run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev
        if: matrix.os == 'ubuntu-latest'
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
      - run: mkdir build
      - run: flutter config --enable-${{ matrix.platfrom }}-desktop
      - run: flutter pub get
      - run: dart compile exe bin/drc.dart -v -o build/${{ matrix.output-name }}
      - run: flutter build ${{ matrix.platfrom }}
      - name: Print Build Files
        run: find build
        shell: bash
      - name: Upload Command Tools
        uses: actions/upload-artifact@v2
        with:
          name: drc-cli-${{ matrix.platfrom }}
          path: build/${{ matrix.output-name }}
      - name: Upload Client
        uses: actions/upload-artifact@v2
        with:
          name: drc-client-${{ matrix.platfrom }}
          path: ${{ matrix.bundle-path }}